### ISSUE TITLE
Fortran file not properly formatted

### ISSUE THREAD

**Issue by davidpasquale** [PDConSec/vsc-print#166]
Hi, I am trying to print a f90 file, but it seams that is not properly formatted.
The problem is:
if a line is longer then the actual size of the page, the text is truncated and not splitted in multiple lines.

![image](https://user-images.githubusercontent.com/15691571/198293066-18571fca-d833-416d-aa9b-c2d178f5ea21.png)

In addition, can you add the possibility of choosing a custom text file size? not limited to 13pt.

It works fine for python files.

Thank you

**Comment by PeterWone** [comment]
You can set a custom font size by [editing your settings file directly](https://code.visualstudio.com/docs/getstarted/settings#_settingsjson). 

Please attach a sample Fortran file to help me reproduce the problem you are seeing. Just paste the first 20 lines of that file you screen snapped.

**Comment by davidpasquale** [comment]
Hi, 
I have installed:
C/C++, C/C++ Extension Pack and C/C++ Themes
Modern Fortran
Fortran Intellisense
Fortran Breakpoint Support

BTW, probably I found the issue, if you do not have spaces between variables the printer does not break the line at the comma.
is it requiring space between the comma and the next variable name?
take a look at line 17

I have anyway the problem that syntax highlighting is not properly rendered in the printer for all the keyword as show in the code

Thank you so much!

P.S. rename testcode.f90.txt in testcpde.f90
[testcode.f90.txt](https://github.com/PDConSec/vsc-print/files/9886805/testcode.f90.txt)
[testcode.f90.pdf](https://github.com/PDConSec/vsc-print/files/9886785/testcode.f90.pdf)
![image](https://user-images.githubusercontent.com/15691571/198545359-14203623-0b80-4da5-86c5-4c8a3003fd61.png)

**Comment by PeterWone** [comment]
# The breaking of lines
Print jobs are rendered as HTML so that CSS can be used to style and colour language elements. You are correct: line wrapping occurs at whitespace.

For most modern languages this is suitable, so the matter has never before been raised. 

Can this situation be improved? Yes. I can post-process the print-job and insert a `<wbr>` (word break opportunity) tag after `)`, `]`, `}`, `=` and `,` which should resolve the line-breaking problem. In the interim, your idea of adding space will also resolve the problem.

# Syntax colouring 

Syntax colouring is done using the highlightjs library. This supports a large number of colour schemes, some of them in common with Visual Studio Code. The Print extension does not allow use of dark themes because printer paper is white, so dark themes are unsuitable. It is possible to force the background colour to white, but this generally produces poor contrast and a washed-out appearance in the print-out. 

I did put some effort into trying to automate remapping of dark themes to light. This is like golf: easy to do, very hard to do a good job consistently. Eventually this was dropped in favour of allowing the user to choose a colour scheme for printing.

If you would like to experiment with colour schemes on Fortran, open this link https://highlightjs.org/static/demo/ and choose the scientific category. Then click through the light themes until you find one that suits your preferences. Most of these are available from Print.

**Comment by PeterWone** [comment]
I have added code to insert optional wordbreaks after ), ], } and comma. This will appear in the next release.
