### ISSUE TITLE
Styling bug for cucumner feature file when Cucumber (Gherkin) Language Support is installed

### ISSUE THREAD

**Issue by Shu-Ting-Huang** [PDConSec/vsc-print#191]
I have installed [Cucumber (Gherkin) Language Support](https://marketplace.visualstudio.com/items?itemName=alexkrechik.cucumberautocomplete) and created the following feature file.
![2023-03-01_22-40-54](https://user-images.githubusercontent.com/57234743/222325945-2a719631-a08a-4abd-a7de-095e2b7621b8.png)
When I tried to print this file, the single-quoted string on line 6 is not rendered as what is rendered on the editor.
![2023-03-01_22-48-20](https://user-images.githubusercontent.com/57234743/222326334-1ceb4ffd-2cc0-426a-84e9-3d555ce2813e.png)

**Comment by PeterWone** [comment]
Syntax colouring is delegated to the highlightjs project at https://github.com/highlightjs/highlight.js

You can contribute enhancements and corrections there.

**Comment by PeterWone** [comment]
@Shu-Ting-Huang I'm closing this issue since it won't be resolved here. 

I thought you'd like to know: the latest major release of highlight.js creates webpack and Typescript problems that break my entire toolchain, so I am now looking for an alternative. While the built-in vscode syntax coloring support is not designed for rendering a whole document, it would nevertheless be an outstanding option if I could get it to work.
