### ISSUE TITLE
Print built-in markdown preview

### ISSUE THREAD

**Issue by sanxing-chen** [PDConSec/vsc-print#192]
Is it possible to print the same as the built-in markdown preview rendering?

https://github.com/microsoft/vscode/issues/109237

**Comment by PeterWone** [comment]
With the software as it is? 

No. The default renderer (the one used for source code) uses highlight.js. 

Can you change the way it renders?

Yes. You have two ways.

1. You can create your own renderer as a separate extension and install it so that the Print extension will use it. There is an API for doing that and there is a complete sample you can use as a basis.
2. You can contribute to the highlight.js library.

**Comment by sanxing-chen** [comment]
Technically is it difficult to get the html content from vscode's rendered results and then print it? This could be ideal in many cases as it will keep rendering results from other extension and theme, etc., without configuring them all over again. Like mentioned in the vscode issue I referred to, also in this https://github.com/PDConSec/vsc-print/issues/161 case.

**Comment by PeterWone** [comment]
Sorry I just realised you are asking about rendered Markdown, not source code.

We hijack the VS Code Markdown pipeline. That's why Markdown extensions like Math+Markdown that allow you to use LaTeX notation for mathematics work for printing. 

Jupyter notebooks work differently and they do not use the same Markdown pipeline as the Markdown preview pane. Up to this point there has never been a unified standard for this kind of rendering. The API that I created for Print is the first attempt to unify the process. Up till now everyone has implemented everything themselves in their own way.
