### ISSUE TITLE
Images specified with a URL including percent-encoding characters won't be shown when printing a markdown document

### ISSUE THREAD

**Issue by skystar0227** [PDConSec/vsc-print#259]
Thank you very much for this great vscode extension.
I have used this extension as a markdown printer heavily.

Recently, I found that some images in a markdown print preview are not found.
These images have been specified with a file path including Japanese characters in a markdown.
The message from a preview server when a image is not found shows me that a file path includes percent-encoding characters.
I think that it has been expected that file paths do not include percent-encoding characters but decoded characters.

In my rough attempting, using `decodeURI` function at the following line works for me as a workaround.

https://github.com/PDConSec/vsc-print/blob/3bf153c11994561310af3f6470b16742f17f8e22/src/extension.ts#L84C17-L84C17

**Comment by PeterWone** [comment]
I think you're right about both the nature of the problem and how to fix it. Would you like to raise a PR or would you prefer me to do it?

**Comment by skystar0227** [comment]
Thank you for your offer to let me make a PR. I will try to make a PR to fix this issue in few days, according to the [Security Policy](https://github.com/PDConSec/vsc-print/blob/master/SECURITY.md#so).

You do not have to wait for my PR if you feel better for your quick fix because I am a beginner for vscode extension development, for GitHub PR, and for your project.

**Comment by PeterWone** [comment]
I think this is an excellent first issue. 

In case you aren't certain how to begin, 

1. Fork this repository. 
2. If you don't already have node installed then download and install the latest version.
3. Use VS Code to clone your fork and open the project.
4. In the root of the project, issue the command `npm i` to fetch all of your dependencies.
5. You should be able to press `F5` to compile and launch the extension test host. Make sure that works. A second copy of VS Code will start and it will say in the title bar that it is the extension test host. The extension test host will automatically load the version of the extension that you just compiled even if Print is installed and enabled. 
6. Make your code fix, and test using the extension debug host. You can set breakpoints before you run the extension debug host, or even while it runs. If you modify the extension source code while debugging you must restart the extension debug host. 
7. Because you are working on your own fork of the project you don't need to create a branch; you can commit your changes directly to master. 
8. At this point you are ready to raise your PR. https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

There are other things that must be done for a release, like updating the changelog and the manual. You don't have to worry about those. Just your fix.

**Comment by PeterWone** [comment]
If you want to install it before the next release, bump the version number in package.json and then `gulp package` will create a VSIX file you can install. You'll miss the next official release because your version number will be the same, but you'll get the one after that.
