### ISSUE TITLE
Should this extension work with Mermaid?

### ISSUE THREAD

**Issue by papadeltasierra** [PDConSec/vsc-print#263]
Does this extension support Mermaid?  Appears that it doesn't at present, or I might be doing something wrong or course ;-).

**Comment by PeterWone** [comment]
It would, but VS Code gets in the way.

All the Mermaid extensions I've seen depend on scripts that are requested and executed in the browser.

Print uses the built-in rendering pipeline in order to get the benefit of any Markdown extensions installed as VS Code extensions. However, VS Code rewrites URLs to suit the way resources are served to the built-in Markdown preview. This breaks delivery of the script to your browser because my embedded webserver can't resolve the mutilated URL.

I could un-mangle URLs but the VS Code team changes this with utter disregard for anyone else's needs.

I'm going to start using my own rendering pipeline. I could examine the built-in pipeline to figure out what to load, but that's a fair bit of work and possibly fragile. Alternately there are only handful of really worthwhile Markdown extensions so maybe I should just load all of them and be done with it. That would be simple and reliable but potentially out of synch with the built-in preview. 

Since the only thing the built in preview does that's not already done by Print is scroll synch (when you scroll the source the preview moves with it and vice versa). It's basically a webview with all the content coming from the renderer. I was thinking about making it possible to replace the built in preview.

**Comment by PeterWone** [comment]
I don't know what they call it internally. but you can capture a sample.

1. Turn off the Print and Close option 
2. Print a Markdown document containing a Mermaid diagram

Inspect the page source for a `<script>` tag.

**Comment by papadeltasierra** [comment]
Thanks – I will give it a go.

Paul DS

Sent from Outlook<http://aka.ms/weboutlook>

**Comment by papadeltasierra** [comment]
Peter,

The only <script> I could find was this:

      <script type="text/javascript">
            function printAndClose(enabled) {
                  if (enabled) {
                        window.addEventListener("afterprint", (event) => {
                              fetch("completed").then(window.close);
                        });
                        setTimeout(window.print, 500);
                  }
            }
      </script>

This doesn’t feel like what you were expecting me to see.


Sent from Outlook<http://aka.ms/weboutlook>

**Comment by PeterWone** [comment]
Sorry this is taking so long. I have reports from some users that Mermaid works, but I experience the same problems you do. Something I did notice is that the Mathpix extension seems to cause problems with other extensions.

**Comment by PeterWone** [comment]
Work is underway on the new rendering pipeline. Since we won't be using the internal pipeline there may be a switch to `marked` which is a lot easier to work with. We hope to support LaTex, DOT (Mermaid renders DOT) and SMILES.

**Comment by PeterWone** [comment]
@papadeltasierra thank you for your extended patience. The latest release replaces the entire rendering pipeline and directly supports Mermaid. LaTeX is also partly supported but I have run out of weekend so ship and be damned, as they say.
