### ISSUE TITLE
Support printing what is displayed in the Diff Editor

### ISSUE THREAD

**Issue by Fusyong** [PDConSec/vsc-print#280]
Is it possible to support printing what is displayed in the Diff Editor?

**Comment by PeterWone** [comment]
No because it's not available from a file or an editor buffer.

Print supports installable document renderers. You could create a document renderer that operates on a virtual document derived from a diff operation but you would still have a problem because renderer selection is controlled by document language identifier and there isn't one.

You could invent a new language identifier "diff" and save the virtual document to a temp file then process it from there with a custom renderer. It's an ambitious project. Let me know if you need any technical support while you tackle it.

**Comment by Fusyong** [comment]
Thank you so much for your very inspiring tips.
