### ISSUE TITLE
Can I configure the font size to be used when printing a plain text file?

### ISSUE THREAD

**Issue by electrotype** [PDConSec/vsc-print#308]
I'm trying to increase the font size using `"print.fontSize": "13pt"` but it doesn't seem to change anything when printing a simple ".txt" file. 

I've tried in Firefox and in Brave, same result.

Am I missing something?

Thanks in advance

**Comment by PeterWone** [comment]
Print uses a framework for document renderer plugins. The one for plaintext is separate from the one that renders source code using highlightjs. The renderer plugins are also responsible for generating stylesheets from settings and it would appear I didn't think to bring out the font family and size for plaintext.

We're having built pipeline hassles at the moment but I'll certainly add this to the backlog!

**Comment by steveculshaw** [comment]
Confirm I'm seeing the same issue in Edge

**Comment by PeterWone** [comment]
See also #309 

Both are addressed by updating the plaintext document renderer to link the `bundled/settings.css` resource also used by the source code document renderer. 

This stylesheet is generated from a template into which system settings are copied. Specifically, these settings

![image](https://github.com/PDConSec/vsc-print/assets/5498936/135a3b33-770b-41e2-bcb6-6d2854b19fad)

**Comment by PeterWone** [comment]
Issue response times have been long lately partly due to the borked build pipeline and partly due to things at work and at home. If you are well pleased with Print and the way it's evolving please consider leaving a favourable review - especially if you have something specific to note. 

Negative feedback belongs here in the issues where I can do something about it - so thank you for helping

**Comment by steveculshaw** [comment]
Thanks for all the hard work 👍
Will do
