### ISSUE TITLE
Revise the decision to change the rendering pipeline!

### ISSUE THREAD

**Issue by IfxBaderG** [PDConSec/vsc-print#326]
With previous method to use the VS Code rendering pipeline plus [Markdown Kroki](https://marketplace.visualstudio.com/items?itemName=pomdtr.markdown-kroki) extension, you were able to render a ton of different diagram types directly in your markdown files.
This functionality is now lost! Now you have to support everything on your own (e.g. https://github.com/PDConSec/vsc-print/issues/322 etc.).

I considered the method to use the VS Cide rendering pipeline a very smart design decision to reuse existing functionality and not having to implement again and again the support for new diagrams.
When it is rendered in VS Code correctly ba any extension, then it were also able to print it with your extension.

@PeterWone So please, revise this decision or bring back the old method via configuration option.

**Comment by PeterWone** [comment]
I'll make it possible to select the renderer.

We're abandoning the built in renderer because Microsoft did things that made it impossible for us to support anything that depends on rendering script that runs in the browser ie Mermaid

It's less trouble than you think to support Kroki. It was already under consideration.

________________________________
From: IfxBaderG ***@***.***>
Sent: Wednesday, July 3, 2024 3:31:39 pm
To: PDConSec/vsc-print ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [PDConSec/vsc-print] Revise the decision to change the rendering pipeline! (Issue #326)


With previous method to use the VS Code rendering pipeline plus Markdown Kroki<https://marketplace.visualstudio.com/items?itemName=pomdtr.markdown-kroki> extension, you were able to render a ton of different diagrams directly in your markdown files.
This functionality is now lost! Now you have to support everything on your own (e.g. #322<https://github.com/PDConSec/vsc-print/issues/322> etc.).

I considered the method to use the VS Cide rendering pipeline a very smart design decision to reuse existing functionality an not having to implement again and again the support for new diagrams.
When it is rendered in VS Code correctly ba any extension, then it were also able to print it with your extension.

So please, revise this decision or bring back the old method via configuration option.

**Comment by PeterWone** [comment]
Try 0.12.5

Didn't revert rendering pipeline. Did support Kroki. If you have a local Kroki server there is a setting for the URL to it.

**Comment by IfxBaderG** [comment]
Hi Peter,

Sry, the Kroki rendering is not working with your extension v0.12.8.
![image](https://github.com/PDConSec/vsc-print/assets/153087358/394e1da1-09e9-470f-b116-6a122a1bd392)

And with the missing `printAndClose` setting it is impossible to look in detail on the HTML output.

Expected output:
![image](https://github.com/PDConSec/vsc-print/assets/153087358/afdb336e-4158-4133-92e4-3e61d96da120)

[kroki_diagrams.md](https://github.com/user-attachments/files/16122950/kroki_diagrams.md)

BR,
Gregor

**Comment by PeterWone** [comment]
I tested with Mermaid diagrams because that's what I had on hand. They work, but thanks very much for the comprehensive test document, which made it trivial to reproduce the problem. A

**Comment by PeterWone** [comment]
Try 0.12.9, I tested with your sample.

**Comment by PeterWone** [comment]
![image](https://github.com/PDConSec/vsc-print/assets/5498936/085776ca-7bd7-4321-a7c9-cb56825ed06b)

There weren't any diagnostic logs surrounding the very new Kroki handling but there are now in 0.12.10

Thank you for your ongoing assistance.

I am testing with local Kroki, very recently stood up. While obviously Print must be a lot more robust than this, possibly it's time to update the company Kroki? but don't do that till we get this sorted!

**Comment by IfxBaderG** [comment]
Our server is up to date with v0.25.0, so I do not expect problem here.

The HTML preview is giving following output "fetch failed", so I suspect this line has exception: https://github.com/PDConSec/vsc-print/blob/master/src/renderers/processMarkdown.ts#L60C45-L60C53

Improving the error logging for `fetch()` exceptions (see discussion here https://github.com/vercel/next.js/issues/49896) might reveal more details.

My guess would be certificate problems in TLS handshake or something in that area with `fetch()`.

**Comment by PeterWone** [comment]
I'm using the fetch that's baked into Node so I'm not really sure how to respond to that.

**Comment by PeterWone** [comment]
I get fetch failed from my local server when I try to use https. The default setup is http, not https. You aren't trying to use https://something:8000 are you?

**Comment by IfxBaderG** [comment]
https:// is mandatory to be used.

**Comment by PeterWone** [comment]
If that's the problem you can tell node where your additional certs are

```bash
export NODE_EXTRA_CA_CERTS=/path/to/your/ca.crt
```

on Windows it's

```
set NODE_EXTRA_CA_CERTS=C:\stuffed\subfolder\thefile.pem
```

**Comment by PeterWone** [comment]
Also get 0.12.12 and try this new setting. I don't have any invalid certs on my network, so I haven't validated this except to the extent that it doesn't seem to break anything. You'll want 12 anyway because the resource resolver is now async to stop diagram rendering from stalling page generation. It was originally designed for pulling fast loading static resources from the bundle, not on-the-fly resources from page-embedded source. For this use it had to become a caching proxy.

**Comment by IfxBaderG** [comment]
v0.12.12 is working perfectly out of the box!
I did not change the setting `print.rejectUnauthorisedTls`.

**Comment by PeterWone** [comment]
Well isn't that just fascinating. To implement the setting I had to switch from Node's built-in `fetch` to using Axios (a popular library) because the built-in fetch lacks an option for this.

It would appear we have found a node bug.

**Comment by PeterWone** [comment]
There will be another release, hopefully this evening after work (it's 15:36 here right now) which uses a double cache
  - when there's a miss it tries to use the hash to load from disk thereby demand-populating the in-memory cache
  - when that also fails it renders, updates the in-memory cache and the disk cache
  - because the key is a hash of the diagram source, if you paste the diagram into another document, you'll still get a file cache hit

**Comment by IfxBaderG** [comment]
⚠️ Another challenge for the renderer.

We are using the extension `jebbs.plantuml` v2.18.1 which supports the PlantUML `!include` directive for local files.
This is essential for maintaining a single source of information for various software components. Additionally we are using an extensive set of preprocessing directives collected in a library include files.

The extension is setup correctly and the preview is WYSIWYG. But `Print` fails here.
![image](https://github.com/PDConSec/vsc-print/assets/153087358/23d85cf0-a13b-468b-b9e1-4dc648fff05a)

HTML Preview:
![image](https://github.com/PDConSec/vsc-print/assets/153087358/7d989d90-7b88-4753-8099-75c87cc73560)

[plantuml.md](https://github.com/user-attachments/files/16172612/plantuml.md)
[classA.iuml.txt](https://github.com/user-attachments/files/16172618/classA.iuml.txt)
[classB.iuml.txt](https://github.com/user-attachments/files/16172619/classB.iuml.txt)

**Comment by PeterWone** [comment]
I've had a good look, and as far as I can see the functional difference between this and a Kroki call to PlantUML is the resolution of include directives. 

- Is that reasonable?
- Is it complete?

**Comment by PeterWone** [comment]
![image](https://github.com/user-attachments/assets/43d1bc2d-28e4-4725-82b0-91d4cba6b255)

**Comment by PeterWone** [comment]
Note that the way I implemented this you can now use it with any Kroki diagram.

**Comment by PeterWone** [comment]
If you have any further requirements please raise new issues
