### ISSUE TITLE
Inline code not rendered if followed by another character.

### ISSUE THREAD

**Issue by gilgaTheDev** [PDConSec/vsc-print#355]
I typed this:
![image](https://github.com/user-attachments/assets/aa835170-fa62-4147-a554-ecd88b23b573)

the output is this:
![image](https://github.com/user-attachments/assets/b6a1692e-4e50-49a3-b1e0-945917208bad)

So, there is a bug when the inline code is directly followed by a character, when it's a letter specifically.

**Comment by PeterWone** [comment]
Print does not support that notation. At a guess, you have installed one of the KATEX extensions and that snap is taken from the preview inside VS Code. 

Print uses `$$` for both inline and block formulae inferring the mode (block or inline) based on whether there is a linebreak between the start and end of the formula. 

`$$` was chosen over `$` because `$` often occurs in text. 

![image](https://github.com/user-attachments/assets/fb9a58bc-8b67-4661-84f7-fa0c2ae2456a)

As you can see it renders just fine in the browser preview provided by Print.

![image](https://github.com/user-attachments/assets/577d4eda-b484-475e-9f7f-dadc2dc766f5)

I realise your example may be intentionally trivial for demonstration purposes, but for the record, for simple stuff like this you're better off using HTML entities like this `It measures 10 &mu;m.` It measures 10 &mu;m.
